### ISSUE TITLE
Are there any examples to parse EDI 204 From this library

### ISSUE THREAD

**Issue by logicdefyer** [indice-co/EDI.Net#129]
Hi , it seems we cannot find a model or a interchange for Edi 204 for this library , i am seeing some issues logged in git-hub for this , is there any chance of an interchange existing.

**Comment by cleftheris** [comment]
Hi and thanks for your interest in [EDI.Net](https://github.com/indice-co/EDI.Net)

unfortunately there is no test sample for the transmission you are referring to.

You could try asking a question on stackoverflow with the tag `edi-net` in order to reach a broader audience. 

Last there are good examples you can checkout inside the repository under the tests project. 

If you get something to work and want to share back feelfree to open a pull request.

Regards,

C.
