### ISSUE TITLE
Parsing text with random escape characters

### ISSUE THREAD

**Issue by GVG** [indice-co/EDI.Net#157]
Hello! I have an issue with EDIFACT parser when it reads random escape characters (which are not supposed to be there really).
Example: `COM+support?@support.riv.ca:EM'`
`?` is followed by `@` which is not service/special character.
This segment throws an [exception](https://github.com/indice-co/EDI.Net/blob/master/src/indice.Edi/EdiTextReader.cs#L549). Tech support on partner's side told me that it should be parsed like there is no `?` sign at all.
Also I've read EDIFACT specification and it doesn't mention anything critical about it.
I see 2 options there:
1. Don't throw exception in this case and continue reading document.
2. Add an option to disable throwing this exception.

**Comment by cleftheris** [comment]
Hmm this seems to me as invalid transmission. But then again you can never be completely certain on this matter. I can see to some changes so that when someone uses the an aditional range of scecial characters list in the Grammar object the parser will consider them as subject to escaping. That will work in your case but it needs modifications. 

Can you also send me the Control advise for this transmission if present.

**Comment by GVG** [comment]
I see no reason why parsing could not be continued after this character. Moreover this is already implemented, but throws an exception instead.
This particular transmission doesn't have UNA segment, thus all service characters are default.

**Comment by cleftheris** [comment]
@GVG ok this makes sense. I will put a flag on the serializer that suppresses bad excape sequense errors.

`SuppressBadExcapeSequenceErrors` a little long but sends the message.

**Comment by GVG** [comment]
@cleftheris thank you very much!

**Comment by cleftheris** [comment]
v1.9.9 is up on nuget 
check this test to see usage https://github.com/indice-co/EDI.Net/blob/60000ffba23b7f46da5a560de493cee6c32335da/test/indice.Edi.Tests/EdiTextReaderTests.cs#L1004
