### ISSUE TITLE
Escaping special characters in EdiTextWriter

### ISSUE THREAD

**Issue by dhufnagel** [indice-co/EDI.Net#160]
I am working on a project for german healthcare. The format for data exchange is EdiFact with on modification: The decimal seperator is a colon. I can fix this easily in the grammar, but the colon also needs no to be escaped with the release charakter (a question mark). So for example "a,b" should be escaped to "a?,b" in alphanumerical fields.

How can I achieve this behaviour?

**Comment by cleftheris** [comment]
Hi  @dhufnagel 

Thanks for your interest in the library.

Is there a standard/spec you can point me to that states this. I am curious because as it is now written only delimiters are considered as special characters and escaped in order not to break the structure. The decimal mark cannot break the structure in any way and that is the reason it is not escaped. 

If you have some guidance/documentation please point me to that resource (if possible in English else I will google translate :D )

C.

**Comment by dhufnagel** [comment]
Unfortunatlely not in english because it's a proprietary german format, so it's in german.
The document can be found here: https://www.gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/sonstige_leistungserbringer/technische_anlagen_aktuell_4/Anlage_1_TP5_V14_20200615.pdf

The interesting point is chapter 5.1: (google translate)
> If one of the control characters agreed here (colon, plus sign, comma, question mark, apostrophe) is to be transmitted as a text sign within a field, then must be preceded by the delimiter. It always applies to that subsequent characters.

I managed to add the decimal charakter to the EdiTextWriter array _charEscapeFlags in my workspace.

**Comment by dhufnagel** [comment]
Is it also possible to explicit force decimal digits? The document specifies the number of decimal digits, but with 9(4),V9(2) it's writing 1 instead of 1,00. Is there a way to force it?

**Comment by cleftheris** [comment]
yes it was writen to handle the implicit decimal point when dealing with the UK specific variation TRADACOMS which does not make use of the decimal point. I think it is easy to make it respect the precision without breaking anyone else.

**Comment by cleftheris** [comment]
Hi @dhufnagel I am making some changes in order to make the format (Picture) work nice with the decimal mark. Here is what I have come up with

1) The decimal mark must not be in the picture itself . Instead of this `9(4),V9(2)` you will have to enter `9(4)V9(2)` (the V points the framework to the decimal point).
2) If we need padding as well then the following will be respected. 
   - Given this picture `9(4)V9(2)` and value `1.028` will be formatted as `0001,03`
   - Given this picture `9(1)V9(2)` and value `0.028` will be formatted as `0,03`
   - Given this picture `9(0)V9(2)` and value `0.028` will be formatted as `,03`

If you are fine with the above I will send a nuget release. The only thing to see is if I need to make the decimal mark included in the escape sequence or not.

**Comment by dhufnagel** [comment]
Hi @cleftheris . Thanks for your fast response.
As I needed the changes for a project of my client urgently, I solved it in my own fork. Here is how I did it:

https://github.com/indice-co/EDI.Net/compare/master...dhufnagel:master

I changed the decimal mark handling as well has the escaping of the decimal mark. I don't know if the way I did it will break the behaviour on other usages, so I did not created a pull request. If you want, I can do so, or you can use my changes for your own ones. Maybe you come up with better handling, then I will replace my implementation with yours.

**Comment by cleftheris** [comment]
You can checkout new version v1.9.10 on nuget

Also introduced `AddEscapeCharacter('')` on the grammar itself so that you can add any character needed.
More info here https://github.com/indice-co/EDI.Net/blob/034e9e8c3d6273aa4281ce155749032abd9b6558/test/indice.Edi.Tests/EdiTextWriterTests.cs#L111

**Comment by dhufnagel** [comment]
I will try. Thanks a lot for the fast response and changes!

**Comment by dhufnagel** [comment]
Hi,
I think there is some misunderstanding here. The decimal separator does not need to be escaped in an numeric field. I think these changes should be reversed:
https://github.com/indice-co/EDI.Net/commit/034e9e8c3d6273aa4281ce155749032abd9b6558#diff-461f0a1b49ce5b489917dde8b1289e6aR308

**Comment by cleftheris** [comment]
Aha thanks for the head up. I read your initial question again and now it makes sense. I will send a patch asap

**Comment by cleftheris** [comment]
Can you please try again with version v1.9.11 and send feedback.

https://github.com/indice-co/EDI.Net/blob/69f1c9173f5175e77e231fb7c179f36334f99e85/test/indice.Edi.Tests/EdiTextWriterTests.cs#L113

**Comment by dhufnagel** [comment]
It's working fine. Thanks a lot!

**Comment by Charpy49** [comment]
Hello, 
I've the same issue, but I cant figure out to work with  EscapeDecimalMarkInText = false
I serialize to EdiFact
And i have this result
`IMD+F+35+::::Noir mat int?. gun - Gun fonce'`
but I want this result (with out the escape character before the point
`IMD+F+35+::::Noir mat int. gun - Gun fonce'`

I precise that the decimal separator is the point, 
I have the v1.9.11 of the library

thanks in advance
