### ISSUE TITLE
Empty EDI X12 Segments

### ISSUE THREAD

**Issue by NealWalters** [indice-co/EDI.Net#161]
I saw these: 
https://github.com/indice-co/EDI.Net/issues/151
https://github.com/indice-co/EDI.Net/issues/152
https://github.com/indice-co/EDI.Net/issues/153

Will they cover X12 empty segments as well? 
I just serialized my first EDI file, and below is what I got. I don't need the FOB, ITD, TD5, MSG, TC2, AMT segments.  I built my POCO object in memory, so everything started out null. 

Also, do you not built the segment count for the SE segment?  I just plugged in the number 54 to see what would happen.  When I left it out, the SE01 is missing. Seems like the user of the POCO class would not know what number to put there. 

```
ISA*00****ZZ*MEGACORP*ZZ*DEMOCORP*010101*0000*U*00401*000020001*0*P**~
GS*PO*Sender*Receiver*20200706*1834*000009001*X*004010~
ST*850*0001~
BEG**NE*NW001**20200706~
CUR**USD~
REF*WO*WO388271~
FOB*~
ITD*~
TD5*~
MSG*~
PO1*010*40*EA*19.99**VC*ABC123~
PID*****Digital Widget~
MEA***0~
DTM**20200720~
DTM**00010101~
TC2*~
AMT*~
SE*54*0001~
GE*1*000009001~
IEA*0*000020001~
```

Thanks! 
Neal

**Comment by cleftheris** [comment]
Hi @NealWalters 
regarding your first question yes they should cover empty segments for X12 just fine. The same does not work on empty implicit segments from EdiValue decorated properties which turned out more difficult than it sounds.

Regarding segment counts there is an draft work-in-progress for counting segments for the wellknown structures (Groups, Messages, SegmentsInMessages) but not finshed yet. You can track it here #17

**Comment by cleftheris** [comment]
v1.11.0 has control counts so I am closing this issue
