### ISSUE TITLE
Question: How skip UNA segment and how indicate EDI message should have no LF or CR characters ?

### ISSUE THREAD

**Issue by rvandeweyer** [indice-co/EDI.Net#165]
Hi,

I do have some questions regarding an EDIFACT implementation.

- How do I Indicate that i do not want to include a UNA segment (right now it always seems to add one) ?
- Secondly how to indicate I do not want any linefeed characters ... 

Thanks
Ronny

**Comment by cleftheris** [comment]
Hi and thanks for your interest in EDI.Net.

I am currently in vacation and I will reply by memory. 

In regards to line feeds you can omit them by using the Formatting enum. Check the source code to see where you can set the parameter because I don't recall. Also regarding the  service string advice i think that if you set the tag name to null on the grammar passed to the serializer then it will be omitted.
