### ISSUE TITLE
EdiCondition on SegmentGroups

### ISSUE THREAD

**Issue by maximeshift** [indice-co/EDI.Net#171]
Hi,
I have been trying to add EdiCondition to SegmentGroups and this makes me unable to read the segment on which the EdiCondition applies.
I have a file as simple as :
```
AA*1*NAME 1~
BB*ADDITIONAL NAME 1~
```

With two segments:
```cs
[EdiSegment, EdiPath("AA")]
public class AA
{
    [EdiValue("X(3)", Path = "AA/0", Description = "AA01")]
    public string TypeCode { get; set; }

    [EdiValue("X(80)", Path = "AA/1", Description = "AA02")]
    public string Name { get; set; }
}

[EdiSegment, EdiPath("BB")]
public class BB
{
    [EdiValue("X(80)", Path = "BB/0", Description = "BB01")]
    public string Name { get; set; }
}
```

If I define a SegmentGroup with an EdiCondition like:
```cs
[EdiSegmentGroup("AA", "BB"), EdiCondition("1", Path = "AA/0")]
public class TestName
{
    public AA Name {get; set; }
    public BB OtherName { get; set; }
}
```

In this case the SegmentGroup is properly identified but only segment BB is read while AA is used for the condition and left null in my SegmentGroup.

If I change it to :
```cs
[EdiSegment, EdiPath("AA"), EdiSegmentGroup("AA", "BB"), EdiCondition("1", Path = "AA/0")]
public class TestName: AA
{
    public BB OtherName { get; set; }
}
```

I manage to read the content of AA and BB segment. Is it on purpose that if defining an EdiCondition on a SegmentGroup, the segment used in the condition would not be read properly if he is defined aside ? Do I have to always define this segment in the segment group and have both attributes on my class ?

Thanks

**Comment by cleftheris** [comment]
Hi @maximeshift and thanks for your interest in the library. This is by design and not related to conditions and I will try to explain the reason behind this design decision. 

The segment group will not be mapped when defined standalone in a class and this is related to the structure of the EDI format itself. Essentially the segment that defines the beginning of a group is at the same time considered to be a segment & a group. So in order to make the hierarchy bind to the CLR object the group class must **subclass** the starting segment  and **not contain** it as it extends the segment functionality. The rest segments are "inside" the group so they can be properties just fine.

Consider the following visualization for the segment group in order to help your model.
```
CC*1*SOME TEXT~
DD*1*SOME TEXT~
AA*1*NAME 1~
     BB*ADDITIONAL NAME 1~
EE*1*SOME TEXT~
FF*1*SOME TEXT~
GG*1*SOME TEXT~
```
When the reader stumbles upon a new segment it starts searching for the structure to bind the data and it searches for the AA tag. But this segment is two things at once! Hence the inheritance in the model works. The segment group on the other hand is a metastructure that is not present actually in the EDI format.

Although there could be a possibility to support this kind of mapping and I understand how it could feel more natural, it is non the less very difficult to implement considering the forward looking nature of the stream reader and the numerous ways segment groups can be defined (collecetions, nest levels etc).

I hope this cleared things up a bit

**Comment by cleftheris** [comment]
One more thing when subclassing the attributes are inherited too so in your `TestName` class you will only need `EdiSermentGroup` and `EdiCondition` attributes.

```csharp
[EdiSegmentGroup("AA", "BB"), EdiCondition("1", Path = "AA/0")]
public class TestName: AA
{
    public BB OtherName { get; set; }
}
```

**Comment by maximeshift** [comment]
Thanks, I was actually coming back to mention that it was not related to the condition :) 
Thanks for the detailed answer and explanations. Looks clear, I will change my classes accordingly and use the inheritance of attributes.
