### ISSUE TITLE
Deserializing an Edifact file containing an unknown message type

### ISSUE THREAD

**Issue by h0gh** [indice-co/EDI.Net#188]
Hi there,

Is it possible to construct interchange and message objects along the following lines:

```csharp
public class Interchange {
  public MessageBase Message {get;set;}
}

public abstract class MessageBase { ... }

[EdiMessage, EdiCondition("IFTMIN", "UNH/2/0")
public class IftminMessage : MessageBase { ... }

[EdiMessage, EdiCondition("INVOIC", "UNH/2/0")
public class InvoicMessage : MessageBase { ... }
```

So that I can deserialize a file with any type of message in it, without knowing which type up front?

Thank you for the great library

**Comment by cleftheris** [comment]
Hi @h0gh and thanks for your interest in [EDI.Net](https://github.com/indice-co/EDI.Net).

As I remember it should be possible since this is the way that TRADACOMS works. See here for a sample with multiple message types in the same transmission https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/UtilityBill.cs. 

The only problem (missing part) with polymorphism & serialization as far as I can tell is that you will have to introduce some new attribute type that signals the serializer to search for CLR types elsewhere than the current model. There was something similar  that existed in wcf, the KnownTypesAttribute .

**Comment by h0gh** [comment]
Thanks. I don't truly need the inheritance, and I got it working by having N separate adjacent lists of messages for each of the N message types. I had tried this previously, but dismissed it because it caused my program to eat all my memory and crash. This turned out to be because I had an off-by-one error in my Edicondition path. The correct path to the edifact document type is UNH/1/0, not UNH/2/0.

When using the path UNH/2/0, I believe the deserializer gets stuck in an infinite loop in the EdiSerializer.SearchForward method (the do-while in lines 654-665). I can submit a PR with a test exhibiting this behavior if you're interested.

**Comment by cleftheris** [comment]
Hi @h0gh 
Yes a test like this is very helpful!

**Comment by cleftheris** [comment]
There is a new version that addresses the infinite loop issue. Thanks for your contribution!

**Comment by h0gh** [comment]
Thanks!
