### ISSUE TITLE
Are Odette and VDA supported?

### ISSUE THREAD

**Issue by DuyNguyenDaenet** [indice-co/EDI.Net#221]
I have a project that involves Odette and VDA format. Is [EDI.Net](https://github.com/indice-co/EDI.Net) supports these standards? If no, what would I need to do to make it work with these standards? Sorry if it is a dumb question, I am new to this. Thank you very much.

**Comment by cleftheris** [comment]
Hi @DuyNguyenDaenet and thanks for your interest in [EDI.Net](https://github.com/indice-co/EDI.Net).

I am not well familiar with Odette and VDA and they are not supported in the library. As far as I can tell by looking at the spec they could be supported in the future but that would mean a new type of grammar that has rules based solely on text sizes instead of element/component delimiters. This would need significant work that is not in our plans.

**Comment by DuyNguyenDaenet** [comment]
Hi @cleftheris.
After creating this issue, I have done some research. Let me quote from this doc [Odette](https://docs.onenetwork.com/devnet/neo_3.3/platform-user-s-guide/integration/formats/edi/odette): "Originally it developed its own distinct set of messages but now only develops subsets of those EDIFACT messages used by the automotive industry. ODETTE have historically had their own standards but have, since 2000, adopted the EDIFACT standards". So it seems both Odette and VDA have 2 versions: The legacy version and the current version which is a subset of EDIFACT. I am working with the current version of Odette and VDA.

Please correct me if I am wrong. From what I have seen, there are 2 main parts to take care of when using the too. The first one is the grammar of which I can use the EDIFACT grammar for the new Odette and VDA with no modification.

The second thing and the thing that I am doing is creating POCO's models based on Odette's spec and your EDIFACT models as guidelines. So far, I have created 2 models to convert Odette's DELINS and AVIEXP messages in EDI format to POCO and then from the output POCO back to EDI format and compare between the 2 EDI formats. They look almost identical except that the converted EDI file from POCOs does not truncate the "+" and ":" at the end.

For example: The converted EDI file has "<something>++++' ", I believe, the "+" at the end can be removed and the result is "<something>'". Another example is  "+::<something>:::::+", I think the ":" at the end can also be remove which results in "+::<something>+". Hope you can understand what I mean. Is the tool supports that or I need to truncate it by myself?

**Comment by cleftheris** [comment]
Hi @DuyNguyenDaenet 
So if these transmissions have EDIFact compliant counterparts you should be just fine. 
As far as your problem is concerned can you please open a new issue? 
In the new issue please provide with the two edi files (input & output) in order to check the differences because I am not sure I have understood correctly.

Also note that there is something that is called compression in the EDIFact standard that omits consecutive empty elements and components. That you can turn that off in the EdiSerializer https://github.com/indice-co/EDI.Net/blob/0f53ecb8471caca40422769010aef0574726689b/test/indice.Edi.Tests/SerializerTests.cs#L102

**Comment by DuyNguyenDaenet** [comment]
Hi @cleftheris ,

The EnableCompression works perfectly. Thank you very much for your help. I think this issue can be closed now.
