### ISSUE TITLE
.net8

### ISSUE THREAD

**Issue by nathangmahler1987** [indice-co/EDI.Net#259]
perhaps we should include .net 8 so it is more straightforward for new users to contribute and it is the latest LTS version now.

**Comment by cleftheris** [comment]
Hi @nathangmahler1987. As the dotnet core progresses the support for the library should advance. There is no need absolute need to upgrade the dotnet TargetFrameworks moniker though. Since the library does not depend on 3rd party dependencies and does not use any new framework features of dotnet 8 the TargetFrameworks can stay the same. Keep in mind that dotnet 6.0 would be a subset of dotnet 8.0. 

What I would do to support dotnet 8.0 would be 

1. drop 6.0 altogether in favor of 8.0 (which is the latest LTS)
2. Use the latest dotnet 8.0 SDK (8.0.300 I believe) in the global.json
3. Update the appveyor.yaml to reflect to this change so that the build does not break.
4. Ensure that all tests complete successfuly.
