### ISSUE TITLE
Help understanding EdiSegment Path settings

### ISSUE THREAD

**Issue by raisr** [indice-co/EDI.Net#261]
Hi,

sorry, but i can't get my  head around the path addressing. As an example here is a UNB Segment.

`UNB+UNOC:3+109910000+999999999+240315:1342+00384++AO05Q224ke0'`

As far as i understand i use the path to access the the values / components in the segment. So for the given example the values /  components are: 

- UNOC:3
- 109910000
- 999999999
- 240315:1342
- 00384
- `<Empty>`
- AO05Q224ke0

How does the addressing work? I thought it was` Path="<Segment>/<ComponentIndex/ValueIndex>/<ValueIndex>"`
I expected that the following code would grab the values UNOC, 3,  109910000,  999999999. But only UNOC and 3 are mapped. 

```csharp

[EdiSegment, EdiPath("UNB")]
public class InterchangeHeader
{
    [EdiValue("X(4)", Mandatory = true, Path = "UNB/0/0")]
    public string SyntaxType { get; set; }

    [EdiValue("X(1)", Mandatory = true, Path = "UNB/0/1")]
    public string SyntaxVersion { get; set; }

    [EdiValue("X(9)", Mandatory = true, Path = "UNB/1")]
    string Code1 { get; set; }

    [EdiValue("X(9)", Mandatory = true, Path = "UNB/2")]
    string Code2 { get; set; }
}

```

**Comment by cleftheris** [comment]
According to EDIFact (as well as the other 2 standards X12 and Tradacoms) inside of an EDI Segment such as `UNB` there is this a fixed structure. For example in your case.
-  tag: `UNB` 
   - element: `UNOC:3` 
     - component: `UNOC` 
     - component: `3` 
   - element: `109910000`
     - component: `109910000` 
   - element: `999999999`
     - component: `999999999`
   - element: `240315:1342`
     - component: `240315`
     - component: `1342`
   - element: `00384`
     - component: `00384`
   - element: `<Empty>`
     - component: `<Empty>`
   - element: `AO05Q224ke0`
     - component: `AO05Q224ke0`

A path is composed by these 3 PathFragments separated by `/` like so `<SegmentName>/<ElementIndex>/<ComponentIndex>`. The component index is synonymous to the `<ValueIndex>`

A part (fragment) can be either:
1. Explicitly declared (full path)
2. a wildcard `*` in order to enable CLR class reusability. In essence this enables a definition on an `[EdiElement]` class as a set of reusable component values under a different Segment context.
3. Missing a part. This case is either because it is implied zero (on a component/value property) or because it is marked on an Element or Segment class.

Check out an older question here https://github.com/indice-co/EDI.Net/issues/179

**Comment by raisr** [comment]
Thanks. That helped me.

**Comment by cleftheris** [comment]
I forgot to mention that in cases where elements repeat multiple times (with variable count) inside of a Segment there is a special notation on order to map them to a collection instead of mapping them to multiple properties of the same type like Element1, Element2, ElementN

Like in this case: https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/EdiFact_Issue190.cs
