### ISSUE TITLE
List wih repeating elements

### ISSUE THREAD

**Issue by xperteer** [indice-co/EDI.Net#263]
Hello guys,

I am having trouble with repeating values in an EDI Fact segment:

Target should be this:
`GIN+AW+9998219+9998218+9998217+9998216+9998215'`

The code I tried so far
```csharp

[EdiValue("X(3)", Path = "GIN/0/0")]
public string Qualifier { get; set; }

[EdiPath("GIN/*")]
private List<IdentityNumber> IdentityNumbers { get; set; }

[EdiPath("GIN")]
public class IdentityNumber
{
    [EdiValue("X(35)", Path = "GIN/1..*")]
    public string Text { get; set; }

}

```

The list is not considered. The output is always this:
GIN+ML'

I saw a few issues with list element, but did not find any workaround. 
So any help would be greatly appreciated.

Cheers
Xperteer

**Comment by cleftheris** [comment]
I suspect you want to serialize, 

am I correct?

**Comment by xperteer** [comment]
Yes sorry I forgot I want to serialize

**Comment by cleftheris** [comment]
You can checkout the test I reference in the commit above  https://github.com/indice-co/EDI.Net/commit/70a36745acf54046936777544bde70cce368c41e.  

But your main issue even if the path annotations where right would be that your List property is marked as private so the serializer would not even pick it up.

The correct path annotations would be as the follow in snippet:

```csharp 
    [EdiSegment, EdiPath("GIN")]
    public class GIN
    {
        [EdiValue("X(3)", Path = "GIN/0/0")]
        public string Qualifier { get; set; }

        [EdiPath("GIN/1..*")]
        public List<IdentityNumber> IdentityNumbers { get; set; }

        [EdiElement]
        public class IdentityNumber
        {
            [EdiValue("X(35)", Path = "*/*/0")]
            public string Text { get; set; }

        }
    }
```

1. The list path annotates the list structure not the list item itself so `[EdiPath("GIN/1..*")]` goes to  `List<IdentityNumber>` prop
2. The structure that contains the values that repeat must be annotated as `[EdiElement]`. No need to declare a path here since it is defined on the list property.
3. The `IdentityNumber` element class must have all its component value properties annotated with wildcard paths for the element index so it can be substituted by the serializer. 
4. (Optional) since the IdentityNumber class may be encountered under a different segment context as a reusable element you can also wildcard the segment name.

**Comment by xperteer** [comment]
Sorry I was on holiday. 

Just tried out and works like a charm. Thanks a lot.
