### ISSUE TITLE
TradaComs26v3 file Charge lines contain `=` sign in TCOD TariffDescription

### ISSUE THREAD

**Issue by ianpowell2017** [indice-co/EDI.Net#268]
Hi, I am a NOOB when it comes to EDI files and so far I have 1.5 weeks of experience!

In a TradaComs file the vendor seems to think its ok to have `=` in the Tariff Description below

`CCD=13+4+:Additional Cyclic Re (Balance to be charged=20.26)+:::+++++++++++83000+1000:ZZ:+++83000+83:+A+S+20000+'`

Please advise how I should parse this and the presence of the `=` sign in the Tariff Description causing the VATP Vat Rate percentage to be parsed incorrectly.

**Comment by ianpowell2017** [comment]
Further research https://www.ibm.com/docs/en/i/7.3?topic=clause-symbols-used-in-picture shows that X(40) should allow 40 characters from the EBCDIC character set.
https://en.wikipedia.org/wiki/EBCDIC shows that `(` `)` and `=` are valid characters

**Comment by cleftheris** [comment]
Hi @ianpowell2017 and thanks for your interest in the library.

Generally in any of the 3 well known EDI formats the grammar is what makes the allowed character set. The only invalid chracters would be those that are part of the grammar delimiters. And in many cases even those can be escaped so that they can take part of a component value. Keep in mind that generally Tradacoms is the UK style of EDIFact. They are in a sense verry similar with slight differences in conventions about the implicit tags/segments they use for groups messages as well as default chracters they use for delimiters/separators.

Are you trying to serialize or deserialize?

**Comment by ianpowell2017** [comment]
Hi, thanks for the response.
I am trying to deserialise and I get errors when the sender includes `=` in the text.

**Comment by cleftheris** [comment]
You can check out the nuget package for the v2.0.0-beta02 that contains this enhancement.
