### ISSUE TITLE
How to deserialize X12 waht include same element in multi segments

### ISSUE THREAD

**Issue by wainlake** [indice-co/EDI.Net#27]
Hi @cleftheris , we got a  850 X12 file from our partner, it include the element 'MSG' in multi segments. We created a C# class to deserialize it, but can not get 'MSG' value in PO detail. How to fix this problem?Thanks.

850 edi & C# class:[X12_850.zip](https://github.com/indice-co/EDI.Net/files/577741/X12_850.zip)
850 Spec:
![850 spec](https://cloud.githubusercontent.com/assets/17489167/20093563/43efa49e-a5d8-11e6-8230-96f8489a5dc6.png)

**Comment by cleftheris** [comment]
@wainlake I am currently looking into this

**Comment by cleftheris** [comment]
The main problem with how you have modelled your classes is the following.

You have decorated the `DTM` class to always create a new structural group using the `SegmentGroupAttribute`. This is not the case for DTM as it is not defining a segment-loop by itself. Also this structure did not declare a terminating marker (SequenceEnd segment) thus the deserializer was trying to put everything after the `DTM` (TC2,MSG, etc...) under that class.

Checkout an improved version of your [PurchaseOrder class here](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/X12_850.cs)

**Comment by wainlake** [comment]
@cleftheris Thanks. Or perhaps I'm making too much of it. It's fine now. EDI.NET is too nice. 

The other question is about the data type. If I defined one element as "9(2)" and the given value is 1,it'll serialize to "Z1".How to fix it? 

Btw, I think the [SE Segment](https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/X12_850.cs#L119) should be located at the bottom of transaction set, is it a clerical error?

**Comment by cleftheris** [comment]
@wainlake glad to hear its working out for you. 
So about your questions

1. As a workaround mark the picture as `9(1)`. __For the explanation:__ The thing with [picture](https://github.com/indice-co/EDI.Net#the-picture-clause) syntax is that I have not made up my mind how to treat it when we are serializing back to edi text file. I have an open ticket where I am thinking about this #23. The `Z` is commonly used for padding a number that otherwise would have to be fixed length when represented as text. Say for the number `24` when written to text in a edi component with a fixed length of `3` then it must be padded as ether `Z24` or `024` or even ` 24`. I am trying to figure out what is the best way to handle this. 
2. for well known structural __segments__ such as those that mark the interchange, group, and message boundaries the order is well known internally and the values are sorted before writing no matter how they are laid out inside your class. For all the other __segments__ the order is important. Internal values found on segments (Component) on the other hand are already indexed so the order is taken care of by the path.
