### ISSUE TITLE
Deserialize then reserialize of x12.850.edi has different result? 

### ISSUE THREAD

**Issue by VhatAmI** [indice-co/EDI.Net#68]
First, let me say I only ever heard of EDI 2 days ago... so I might be just ignorant of how it works.

I took the sample file x12.850.edi and deserialized it and reserialized it like so : 

```
` var X12grammar = EdiGrammar.NewX12();` 

`var interchange = default(Interchanges.PurchaseOrder_850);
            using (var stream = new StreamReader(@"c:\moo\x12.850.edi"))
            {
                interchange = new EdiSerializer().Deserialize<Interchanges.PurchaseOrder_850>(stream, X12grammar);
            }`

`var output = new StringBuilder();
            using (var writer = new EdiTextWriter(new StringWriter(output), X12grammar))
            {
                new EdiSerializer().Serialize(writer, interchange);
            }
            string result = output.ToString();
            System.IO.File.WriteAllText(@"c:\moo\result.edi", result);`

```

Now the files at first glance looked about the same but then I noticed some things 

*0*T*>~ in the original became 
*1*T*~ 
dropping the > and a 0 was changed to a 1 

After noticing this I compared the 2 files because my expectation was a deserialize reserialize would result in the exact same file...
![image](https://user-images.githubusercontent.com/10841983/31298163-742caa9a-aaae-11e7-87dc-69d53c8ff5fb.png)

8 leading 0s were added to a 2 in the next line

a line CUR**~ was added etc.

state and zip dropped from the address 

Am I using the library wrong here? Interchanges.PurchaseOrder_850 is from https://github.com/indice-co/EDI.Net/blob/master/test/indice.Edi.Tests/Models/X12_850.cs

Am I overlooking something or have I missed something?
Again very new to EDI so my apologies if this is something obvious that I overlooked.

**Comment by cleftheris** [comment]
Hi @VhatAmI and thanks for your interest in [Edi.Net](https://github.com/indice-co/EDI.Net).

First of all there are some things to note about the samples
1. They are good examples of dummy transmission files 
2. The classes made to deserialize them are meant to be an inspiration, more focused on how you could use the libraries features than complete.

Regarding my second point (2) one of the key features of Edi.Net is that it is kind of "domain model" first. This means that someone that only receives EDI files could be using a model with far less properties that the complete transmission describes only to cater his needs. The said model would never completely recreate the incoming message.

Ok now for the actual issues you mentioned.
1. The ISA header has what it is called the character advise section of the transmission which is not fully supported yet for X12 (one cannot negotiate the X12 special characters over the wire) #19 
2. The zero turned into one (this one I don't know without running the test myself. Check the type of the property that this is being deserialized to. If you are not sure about the type always start with `string`)
3. 8 leading 0s added because the `GS/5` was marked on my model as length 9 component `9(9)` change this to `9(1)` and you will be ok. This applies to all numbers if you need padding if you don't stick with `9(1)`
4. The rest are related with EDI compression rules when serializing. These rules are not mandatory but essentialy when implemented they allow one to omit subsequent optional elements and components that have no value. This goes also for null segments. To track when compression will be fully supported check here #48 

While I consider the library to be quite fast and powerful, it is far from perfect. So if you see some improvement that you can contribute to feel free to send me a pull request with your code & test to showcase the fix

**Comment by VhatAmI** [comment]
Thanks for the information ! 

We are still not sure what our particular use cases will be, likely just receiving, but it is possible the company will want to be able to send at some point. I'm just trying to get ahead of it and learn how all this EDI stuff works before the use cases get solidified. 

I donno if I'd be the right person for pull requests since I am still learning EDI but if I get any Interchange files going that I think will be useful for others I'll add them to the library pending your review
