### ISSUE TITLE
optional SegmentGroups

### ISSUE THREAD

**Issue by mlspielt** [indice-co/EDI.Net#75]
I have a lot of SegmentGroups and I don't understand how to set the SequenceEnd correctly.. because I don't know what the next SegmentGroup is. The problem is that some SegmentGroups are skipped, because of that. Is there a way to fix that?

**Comment by cleftheris** [comment]
Hi @mlspielt and thank you for your interest in [Edi.Net](https://github.com/indice-co/EDI.Net).

Unfortunately there is no way at the moment to break out of a sequence if you don't know a fixed following segment name. At the beginning when I added support for segment groups I was thinking that it would be a hassle to have to define all possible segment names on the attribute. Apparently this was not the best decision. 

As I see it what needs to be done Is to add support on the attribute itself to declare an array of participating segment names. When a segment that is not on the list appears then the segment group breaks free. 

This seems as a moderate task but it is not as easy not to brak stuff. If you got the time to spare give it a try and submit a pull request. If you decide to do so please provide with additional tests that prove the case . 

Regards

**Comment by mlspielt** [comment]
Thank you for the quick answer, I will look into it.

**Comment by dfyx** [comment]
Hey, @mlspielt asked me to help him out and I think I found a rather elegant solution.

The underlying issue is that the format we have to parse (routing information for German health care invoices) works with an implicit tree structure without end tags. I think the best way to handle this is to just walk up the stack whenever no matching property for a segment is found. That way you don't even need to set `SequenceEnd` in cases where there's no explicit end tag.

I've hidden that functionality behind a configuration flag on `EdiSerializer` so it won't break existing code. I'll send a pull request in a few minutes.

**Comment by cleftheris** [comment]
@dfyx This is very clever. I will send an update asap
