### ISSUE TITLE
Need help to create Poco class for EDI 856

### ISSUE THREAD

**Issue by yashpalsingh6840** [indice-co/EDI.Net#93]
Hi,

I am very new to EDI. Can someone please help me to create Poco classes for EDI 856. I dont find this class in test project associated in this repo.

I know this is not an issue to report here, but I dont know where else to put my request or seek help regarding this.

Thanks in advance.

**Comment by cleftheris** [comment]
Hi @yashpalsingh6840 thanks for your interest to the library. 

The reason you cannot find the class is because the tests are there merely to act as guidance as well as insurance that the lib works as expected. They are not considered as complete.

I think in order to help you get started, you should check an answer to a similar question here #80. Check the last comment by @gk7gk7
